### ISSUE TITLE
ImportError: No module named 'IPython.Shell' on exception in IPython 3.0.0

### ISSUE THREAD

**Issue by kelvin22** [smurfix/flask-script#129]
After upgrading to IPython 3.0.0, `python manage.py shell` succesfully brings up IPython shell, however the following error is raised when any exception occurs.

```
In [1]: hi
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/Users/kelvin/.virtualenvs/aero3/lib/python3.4/site-packages/flask_script/commands.py in run(self, no_ipython, no_bpython)
    299                     # 0.10.x
--> 300                     from IPython.Shell import IPShellEmbed
    301                     ipshell = IPShellEmbed(banner=self.banner)

ImportError: No module named 'IPython.Shell'

During handling of the above exception, another exception occurred:

NameError                                 Traceback (most recent call last)
<ipython-input-1-764efa883dda> in <module>()
----> 1 hi
```

**Comment by hut8** [comment]
I'm getting the same problem. According to [the ipython site](http://ipython.org/ipython-doc/dev/interactive/reference.html#embedding-ipython), it looks like it moved, so the applicable code there should read:

```python
from IPython import embed
embed() # this call anywhere in your program will start IPython
```

**Comment by jeffwidman** [comment]
It looks like this is now fixed in https://github.com/smurfix/flask-script/blob/master/flask_script/commands.py#L305 ? 

I'm not clear if the comments about different versions are regarding iPython or Flask.

**Comment by smurfix** [comment]
Meh. The correct way to do that sort of thing is to default to the new code, and use an error handler for catering to the old.
Anyway. Pulling.

**Comment by jeffwidman** [comment]
Yeah, I considered that, but I couldn't come up with a realistic scenario where anyone who uses iPython is using a version < 0.12 so I didn't see much point in paying the maintenance cost for that extra code...

Unlike most Flask dependancies such as a an ORM or forms library, a Flask project won't have code written around iPython because it's just an external REPL. I couldn't think of a single example of a task in a Flask project where someone might have written code to wrap iPython.

And even if I'm missing something, iPython 0.12 was released over 4 years ago now, so anyone who's thinking about upgrading Flask-Script would benefit far more by upgrading iPython--they've released a lot of useful features. It's not hard to say 'if you want to use an ancient version of iPython, just use an old version of Flask-Script'.

Anyway, I'm happy to change if you want--just explaining my reasoning.

Also, what does 'pulling' mean in the context of your comment? I was confused whether you meant 'pulling' as in closing the issue or 'pulling' as in accepting the PR.

**Comment by smurfix** [comment]
On 04.01.2016 21:15, Jeff Widman wrote:
>
> Anyway, I'm happy to change if you want--just explaining my reasoning.
>
No problem. In this case I agree with you, there's not much point of
keeping compatibility to <0.12.
>
> Also, what does 'pulling' mean in the context of your comment? I was
> confused whether you meant 'pulling' as in closing the issue or
> 'pulling' as in accepting the PR.
>
Both. ;-)

-- 
-- Matthias Urlichs
