### ISSUE TITLE
SQLAlchemy Deprecation Warning when including Flask-Script

### ISSUE THREAD

**Issue by davedg629** [smurfix/flask-script#95]
When I start the flask dev server, I am getting the following warning, but only when I include and initiate a Manager object:

    /sqlalchemy/util/langhelpers.py:689: SADeprecationWarning: Use .target
        obj.__dict__[self.__name__] = result = self.fget(obj)

Here is a link to the line in langhelpers.py that is referenced in the warning - https://github.com/zzzeek/sqlalchemy/blob/rel_0_9_3/lib/sqlalchemy/util/langhelpers.py#L689

Not sure if this is an SQLAlchemy problem or a Flask-Script problem. I'm using up-to-date versions of both (0.9.3 and 0.6.7 respectively).

I'm kind of a n00b so if I need to provide more info, let me know. So far I checked my logs and I don't see any other info about this warning.

**Comment by jeffwidman** [comment]
Closing as an old bug that's likely been fixed in newer releases of either SQLAlchemy or Flask-Script

**Comment by jacquerie** [comment]
Apologies for necroposting, but since you were the only other mention on the internet of the same problem I felt had to : )

Were you by any chance also using `Flask-Admin`? Because I just squashed the same warning there: https://github.com/flask-admin/flask-admin/pull/1447.

In any case to debug this I put a breakpoint inside of [the function](https://github.com/zzzeek/sqlalchemy/blob/9e06ab17b9d3083cd45540f714234d1d5826da32/lib/sqlalchemy/orm/relationships.py#L1641-L1648) that is raising the warning and then inspected the local stacktrace. If you are still having the same issue but you are not using `Flask-Admin` you can debug this in the same way.

**Comment by davedg629** [comment]
Yes, I am using Flask-Admin. I'll have to update my packages. Thanks for finding the problem!
