### ISSUE TITLE
New 2.0.5 version code is not on github

### ISSUE THREAD

**Issue by noirbizarre** [smurfix/flask-script#98]
Hi!

You released the 2.0.5 version on PyPI but the tag and probably the code is not in this repository.

Waht's in the release, what changed ?

**Comment by asteinlein** [comment]
I'm doing an upgrade pass on our dependencies, and reached Flask-Script where I noticed this as well. We can't just upgrade to 2.0.x without any documentation. What's going on with this?

**Comment by asldevi** [comment]
Any updates on this?

**Comment by monkeysecurity** [comment]
+1

**Comment by JeNeSuisPasDave** [comment]
+1

Also, v2.0.5 has a bug that the latest code (v2.0.6) fixes. It would be great you could push an update to pypi with that fix. And also, as per the other comments, update the change log, add a 2.0.5 and 2.0.6 tag, etc.

The bug is on this line of commands.py:

     help='monitor Python files for changes (not 100%% safe for production use)',

That is correct code, and is the current state of the repo, but in the current (v2.0.5) version on pypi and installed by pip, it uses `100%`; the `%` is not escaped and so the help output is corrupted (because argparse.print_help() substitutes _something_ for that formatting argument. On my system I see a dump of a dictionary.

**Comment by jeffwidman** [comment]
Closing this, as it's ultimately two separate issues:

1. outdated changelog (#151)
2. need a new release (#149)

**Comment by rlam3** [comment]
Is it possible to update the documentation with the correct versions? i'm confused between github and flask-script documentation page. Thanks!

**Comment by jeffwidman** [comment]
@rlam3 I *think* RTD docs are built from the GitHub repo, although I wasn't around when it was all setup. RTD lets anyone trigger a build of the latest/stable versions by going to the RTD overview page for the project... I just triggered a new build, so if you're still seeing a discrepancy please file a new bug and I'll take a look. Note that you can look at both `stable` and `latest` on RTD...
